### PR TITLE
Allow empty sse flag in freezer URL.

### PR DESCRIPTION
**Pull request by SpeedyCoder**

### CODE REVIEW

**Comment by mjgarton** [comment]
Why?

**Comment by SpeedyCoder** [comment]
So I can use it without the flag set. It's already geared up to that. It just never gets to this branch https://github.com/uw-labs/substrate/blob/master/freezer/freezer_url.go#L65, because it forces the encryption to be `aes256`.

**Comment by SpeedyCoder** [comment]
It's also inconsistent with freezer url setup, as that uses sse parameter that only allows the value to be in all caps. We should probably be case insensitive in both cases...

**Comment by nick-jones** [comment]
Probably worth pointing out, in case it looks like we're looking to store without server-side encryption: we set up [default encryption](https://docs.aws.amazon.com/AmazonS3/latest/dev/bucket-encryption.html) on all our buckets.

**Pull request merged**
