### PR TITLE
Fix package declaration

### PR DESCRIPTION
**Pull request by mjgarton**
The old one no longer works, so use this.

### CODE REVIEW

**Comment by thinktainer** [comment]
what's with the ci failure?

**Comment by mjgarton** [comment]
Not sure @thinktainer what's going on there.

Actually @ggordan was going to set up CI for substrate.  @ggordan is this a side effect of a not-properly-set-up-yet CI?

**Comment by SpeedyCoder** [comment]
I think that's the case, as there is no circle config in this branch. Also @mjgarton, I would consider adding modules to substrate to be protected from changes like these...

**Comment by ggordan** [comment]
@mjgarton yep I've open a PR for it. I wanted to fix the build issues before opening but seeing as circle is now building and failing PRs due to no config errors, I can do this in a different PR

**Pull request merged**
