### PR TITLE
Expand environment variables of suburl

### PR DESCRIPTION
**Pull request by simonhdickson**
Expands any environment variables in the url passed to suburl

### CODE REVIEW

**Comment by mjgarton** [comment]
Why do this kind of processing in substrate rather than in the calling application?

**Comment by simonhdickson** [comment]
You could do this in the calling application, but it means you have to remember to do this everywhere. Is there a use case you can think of where you wouldn't want to do this?

**Comment by mjgarton** [comment]
I would not want this because I want the application to behave as the documentation suggests it will behave.

Also, would you expect `database/sql` to do similar to this? Or `http.Get()`? It's essentially the same kind of abstraction.  I think variable expansion is useful in a very wide set of use cases, but that's not an argument for building it in to everything.

I think suburl modifying the passed in string is surprising, because I can't think of a single other go library that does this[1] and I also think it's bad practice (except in very specific situations) to reach out and read environment variables from within a library.  It represents an extra hidden input to the call that isn't obvious to the caller.  The way to pass information to a library function is through it's API.  The best way for it to be obvious to the caller IMO is to put it in the caller where a developer can clearly see that it's doing this, and it's only one line.

Having said all of that, if people strongly disagree and want to avoid that extra 1 or 2 lines in the calling app, how about 

* At least including it in the docs?
* Having a different wrapper function that does this, leaving the "plain" one as it is?

That way, it's clear to the caller that it's doing it, because the function they used is named appropriately, and for those who don't want it, they don't have to think about whether environment variable expansion might somehow represent an injection attack they might be vulnerable to, and if they happen to have env var looking bits inside their strings, things will still work?

[1] various things pay attention to cross-application system or user level config such as HTTP_PROXY, but I think that's very different from using it in this way, and it's arguably a workaround for the fact that http libraries historically provided no way to provide this information.

**Comment by thinktainer** [comment]
I concur with the outcome.

**Pull request closed without merging**
