### PR TITLE
Expose fields in the freezer config objects.

### PR DESCRIPTION
**Pull request by SpeedyCoder**

### CODE REVIEW

**Comment by michael-donat** [comment]
Why?

**Comment by SpeedyCoder** [comment]
I want to be able to pass in custom straw storage. It's currently quite weird setup as you can't really initialise freezer sink and source yourself, as you can't access the fields of the config structs. So we should either expose them as I did in this PR or we should only export functions for initialisation via url, as that's the only way to initialise a freezer sink and source currently. Exposing fields of the config structs matches other backend implementations and is more flexible in my opinion.

**Comment by thinktainer** [comment]
I concur. Encountered the same / similar problem in the past and was annoying.

**Comment by SpeedyCoder** [comment]
@mjgarton I wanted an implementation that will stop reading after going through all the existing files. This is what I did for now https://github.com/utilitywarehouse/partner-pkg/blob/freezer/event/freezer/store.go#L81-L95, it might be worth adding this option to freezer if other people want to do the same rather than using a custom straw store that returns a specific error when asked to open a nonexistent file

**Pull request merged**
