### PR TITLE
Relax condition for acknowledgements order for synchronous sink adapter.

### PR DESCRIPTION
**Pull request by SpeedyCoder**
I was hitting this a lot with partitioned Kafka backend, when publishing using the same sink in two different goroutines. My guess is that one broker was faster than another and so I ended up getting acknowledgements in seemingly the wrong order, even though the order fine as I'm performing concurrent writes. Making these changes solved my issue.

### CODE REVIEW

**Comment by bilbercode** [comment]
nice spot, LGTM 👍

**Comment by mjgarton** [comment]
Or.... Did I mis-understand the problem and this is a way to work around kafka (or the driver) doing things out of order, and not your application doing things in multiple goroutines?

**Comment by SpeedyCoder** [comment]
@mjgarton none of the backends have guaranties for the order of acknowledgements when writing messages concurrently. If you want that you need to write them synchronously one by one (i.e. wait for the acknowledgement before writing next message). This just makes the synchronous adapter usable with multiple goroutines that want to write messages one by one and don't care about the order of messages between each other...

**Comment by mjgarton** [comment]
Why are you using the synchronous adapter if you want to have multiple message published in flight at the same time?

**Comment by SpeedyCoder** [comment]
Because I want to write messages from two sources and want to make sure that I write them in the correct order for each of the sources (i.e. synchronously for each of the source), but I don't care about the ordering between them (basically merging two streams). The synchronous adapter is implemented in a way that supports this use case, except this one error case. I think this use case is perfectly valid.

Without this change you can effectively only use the adapter with one goroutine and then there will be at most one unacknowledged message at a time. If this is the way it's supposed to be used, then we can probably simplify the implementation quite a bit, but I would prefer to keep it as it is and add this fix as it makes it more useful.

**Comment by mjgarton** [comment]
Okay I get it now. Thanks for the explanation. This isn't quite the case I was referring to that might hide bus in the caller code, and I see why you might want this change.

LGTM.

**Pull request merged**
